56-no-redirect-when-2fa-missing
memaar92/transcendence pull request #58
Opened 2024-10-02 12:47 UTC by wrottger

2024-10-03 17:25 UTC, memaar92 commented
Kann ich vermutlich morgen genauer testen. Aber wie sind denn meine file commits hier gelandet? Die waren eigentlich nur auf main, weil dort das Email-Banner Bild gehostet wird. Die brauchen eigentlich nicht auf dev

2024-10-04 07:10 UTC, wrottger commented
> Kann ich vermutlich morgen genauer testen. Aber wie sind denn meine file commits hier gelandet? Die waren eigentlich nur auf main, weil dort das Email-Banner Bild gehostet wird. Die brauchen eigentlich nicht auf dev

Ich weiss auch nicht wie die hiergelandet sind :)

2024-10-04 16:52 UTC, memaar92 requested changes
Wollte die Anpassung testen, aber kann keinen neuen user registrieren. Wenn ich bei der Registrierung eine email eingebe und auf den Button klicke, kommt als reponse eine 404 (email existiert noch nicht; was soweit fein ist). Allerdings bleibe ich auf der Seite und komme nicht zur pw-Eingabe. Habe auch nochmal mit dem aktuellen dev-Stand quergecheckt und da funktioniert das Verhalten weiter wie erwartet.

Konnte im Code jedoch keine Stelle finden, die das Verhalten eventuell verursacht. Daher bitte nochmal prüfen.

2024-10-05 15:42 UTC, wrottger commented
@wrottger replace the (!request.ok) so it doesn't catch 404 errors

2024-10-06 09:24 UTC, memaar92 commented
@wrottger bitte nochmal die geaenderte Logik pruefen und vor geupdateten PR selbst testen. Wenn man (!response.ok) (ich glaub du meintest das; ein "!request.ok" hab ich in dem file nicht gefunden) und das zugehoerige else statement rausnimmt, kommt man zwar nun zum registrieren. Allerdings kommt man von dort nun nicht weiter.

2024-10-06 12:48 UTC, memaar92 approved these changes
lgtm. Testing erfolgreich

2024-10-06 12:48 UTC, merged