Live chatv2 giga super mega merge
memaar92/transcendence pull request #76
Opened 2024-10-15 17:01 UTC by Pommfritz0308

**Backend Changes:**

1. ASGI Configuration (asgi.py):
   - Added WebSocket routes for the live_chat app, ensuring chat WebSockets are handled correctly by adding live_chat.routing.websocket_urlpatterns.

2. Settings (settings.py):
   - Added live_chat to INSTALLED_APPS for managing chat functionality.

3. URL Routing (urls.py):
   - Added a new API route for chat: /api/chat/, connecting chat views and WebSocket routing to the application.

4. Live Chat App:
   - Models (models.py):
     - Message: Handles chat messages with fields for sender, receiver, timestamp, and content.
     - Relationship: Manages friend requests and chat relationships between users.
   - Admin (admin.py): Registered Message and Relationship models.
   - Views (views.py):
     - Added views to manage relationships between users (RelationshipStatusView).
     - API endpoints for retrieving and updating relationship status between two users.
   - WebSocket (consumers.py):
     - Implemented ChatConsumer to manage WebSocket connections, sending and receiving messages, and updating the frontend dynamically.
   - Routing (routing.py): Defined WebSocket URL patterns for live chat.

5. Django Admin:
   - Registered Message and Relationship models for Django admin interface.

6. New User Management API (views.py in usermanagement):
   - Added endpoint /users/<str:displayname>/ to retrieve a user’s ID by their display name, used for user search input.

**Frontend Changes:**

1. New Live Chat Interface (live_chat.html):
   - HTML Structure: A responsive chat interface with a chat window, user search field, user list, and message display area.
   - CSS Styling: Defined styles for chat messages, including separate styles for sent (.message-sender) and received (.message-receiver) messages, and timestamp styling.

2. Frontend JavaScript (live-chat.js and chatHandler.js):
   - WebSocket Initialization: Dynamically sets up a WebSocket connection when the chat page is loaded.
   - Real-Time Updates: Handles real-time message sending, receiving, and updating the chat interface with the latest messages.
   - User Management: Includes a dynamic user list and allows users to send friend requests, accept, or block requests in real-time.
   - Chat and game notifications across all pages (except unregistered paths and /game)

3. Chat Room (chat_room.html):
   - Introduced a separate chat room page with message history, input handling, and dynamic user interaction through WebSockets.

4. Frontend Routing (app.js and router.js):
   - Added routes for the new chat and chat room pages.
   - Integrated chat-specific logic into the existing frontend router, ensuring chat functionality is properly initialized.

5. CSS Changes:
   - Chat-Specific Styles (chat.css): Added styles for the chat interface, including the chat window, message items, and user list layout.

2024-10-16 07:49 UTC, stevebalk commented on backend/pong/config.toml
10 seconds is a bit long, isn't it?

2024-10-16 07:51 UTC, stevebalk commented on backend/pong/consumers/matchmaking_consumer.py
Please change it to a log message or remove it if it's no longer needed.

2024-10-16 07:51 UTC, stevebalk commented on backend/pong/consumers/matchmaking_consumer.py
Please change it to a log message or remove it if it's no longer needed.

2024-10-16 07:52 UTC, stevebalk commented on backend/pong/data_managment/user.py
Please remove the methods if we don't need them (You don't use them)

2024-10-16 07:53 UTC, stevebalk commented on backend/pong/match/match_session_handler.py
Please change it to a log message or remove it if it's no longer needed.

2024-10-16 10:37 UTC, memaar92 commented on backend/live_chat/consumers.py
> +    # async def send_current_game_registration(self, user_id):
remove if no longer needed. Also applies to other commented code

2024-10-16 10:37 UTC, memaar92 commented on backend/pong/config.toml
Yeah, could be a bit shorter. Yesterday, I thought 5secs is too short, but now seeing it in action for the first time, I agree that 10secs might be a bit long

2024-10-16 12:37 UTC, memaar92 commented on frontend/js/chatHandler.js
> +        await this.checkToken();
Why is this exactly needed? What would be the issue if the token is not checked?

2024-10-16 12:37 UTC, memaar92 commented on frontend/js/chatHandler.js
> +        await this.checkToken();
Also, what is event code 1006?

2024-10-16 13:18 UTC, memaar92 commented on backend/live_chat/templates/live_chat.html
> +<!DOCTYPE html>
Wird die noch genutzt?

2024-10-16 13:19 UTC, memaar92 commented on backend/live_chat/views.py
> +def live_chat(request):
noch benutzt?

2024-10-16 13:20 UTC, Pommfritz0308 commented on backend/live_chat/views.py
> +def live_chat(request):
nein

2024-10-18 15:16 UTC, memaar92 commented on frontend/js/chatHandler.js
> +    await this.refreshToken();
Immer den Token zu refreshen, egal, ob ein gültiger Access token existiert scheint problematisch zu sein.
Bsp.: Ich logge mich ein und bleibe auf dem main-menu bis der access token abläuft. Dann klicke ich auf Tournament. Sowohl der ChatHandler als auch Wayne's Frontend schicken dann quasi zeitgleich refresh Token-Anfragen. Der eine scheint aber nicht mehr valide zu sein.

2024-10-18 15:17 UTC, memaar92 requested changes
siehe Kommentar zum Token-Refresh. Bitte nochmal ausgiebig testen vor nächstem Push

2024-10-22 16:39 UTC, wrottger commented
#89 should be fixed now

2024-10-23 12:04 UTC, memaar92 approved these changes
Major issues have been fixed and main chat features are working. Well done

2024-10-23 12:04 UTC, merged